// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ParsedWorkoutFormStates.tsx": () => import("../components/mockups/ParsedWorkoutFormStates.tsx"),
  "./components/mockups/TrainingAdjustmentCardStates.tsx": () => import("../components/mockups/TrainingAdjustmentCardStates.tsx")
};
