import { db } from "./index";
import { exerciseLibraryTable } from "./schema/fitness";

const exercises = [
  { name: "Barbell Back Squat", muscleGroup: "legs", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=ultWZbUMPL8", instructions: ["Position the bar on your upper traps", "Stand with feet shoulder-width apart", "Brace your core and unrack the bar", "Lower by bending knees and hips simultaneously", "Descend until thighs are parallel to the floor", "Drive through your heels to stand back up"], commonMistakes: ["Knees caving inward", "Rounding the lower back", "Rising on toes instead of driving through heels", "Not reaching proper depth"], primaryMuscles: ["quadriceps", "glutes"], secondaryMuscles: ["hamstrings", "adductors"], tertiaryMuscles: ["core", "lower back"], alternativeIds: [2, 3] },
  { name: "Front Squat", muscleGroup: "legs", equipment: "barbell", goal: "strength", difficulty: "advanced", youtubeUrl: "https://www.youtube.com/watch?v=m4ytaCJZpl0", instructions: ["Rest bar on front deltoids with elbows high", "Stand with feet shoulder-width apart", "Keep torso upright throughout movement", "Lower by bending knees and hips", "Descend until thighs are parallel", "Drive up maintaining upright position"], commonMistakes: ["Dropping elbows", "Leaning forward excessively", "Wrist pain from poor rack position"], primaryMuscles: ["quadriceps"], secondaryMuscles: ["glutes", "core"], tertiaryMuscles: ["upper back", "hamstrings"], alternativeIds: [1, 3] },
  { name: "Goblet Squat", muscleGroup: "legs", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=MeIiIdhvXT4", instructions: ["Hold dumbbell at chest with both hands", "Stand with feet slightly wider than shoulder-width", "Push hips back and bend knees", "Keep chest up and elbows inside knees", "Lower until thighs are parallel", "Press through heels to stand"], commonMistakes: ["Letting the weight pull you forward", "Not going deep enough", "Knees caving inward"], primaryMuscles: ["quadriceps", "glutes"], secondaryMuscles: ["core"], tertiaryMuscles: ["forearms", "upper back"], alternativeIds: [1, 2] },
  { name: "Conventional Deadlift", muscleGroup: "back", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=op9kVnSso6Q", instructions: ["Stand with feet hip-width apart, bar over mid-foot", "Hinge at hips and grip the bar outside knees", "Flatten your back and brace your core", "Drive through the floor pushing hips forward", "Lock out at the top with shoulders back", "Reverse the motion to lower the bar"], commonMistakes: ["Rounding the lower back", "Jerking the bar off the floor", "Bar drifting away from body", "Hyperextending at lockout"], primaryMuscles: ["hamstrings", "glutes", "lower back"], secondaryMuscles: ["quadriceps", "traps"], tertiaryMuscles: ["forearms", "core", "lats"], alternativeIds: [5, 6] },
  { name: "Romanian Deadlift", muscleGroup: "back", equipment: "barbell", goal: "hypertrophy", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=7j-2w4-P14I", instructions: ["Hold barbell with overhand grip at hip level", "Slight bend in knees, maintain throughout", "Push hips back while lowering the bar", "Keep bar close to legs", "Lower until stretch in hamstrings", "Drive hips forward to return"], commonMistakes: ["Bending knees too much", "Rounding upper back", "Not feeling hamstring stretch"], primaryMuscles: ["hamstrings", "glutes"], secondaryMuscles: ["lower back"], tertiaryMuscles: ["forearms", "core"], alternativeIds: [4, 6] },
  { name: "Sumo Deadlift", muscleGroup: "legs", equipment: "barbell", goal: "strength", difficulty: "advanced", youtubeUrl: "https://www.youtube.com/watch?v=y2MnZGcgjU8", instructions: ["Wide stance with toes pointed out 45 degrees", "Grip bar inside your knees", "Push knees out over toes", "Drive through feet spreading the floor", "Keep chest up throughout", "Lock out hips and knees together"], commonMistakes: ["Hips shooting up too fast", "Knees caving in", "Stance too wide or narrow"], primaryMuscles: ["quadriceps", "glutes"], secondaryMuscles: ["hamstrings", "adductors"], tertiaryMuscles: ["lower back", "core"], alternativeIds: [4, 5] },
  { name: "Barbell Bench Press", muscleGroup: "chest", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=rT7DgCr-3pg", instructions: ["Lie on bench with eyes under bar", "Grip bar slightly wider than shoulder-width", "Retract and depress shoulder blades", "Unrack bar and position over chest", "Lower bar to mid-chest with control", "Press bar up and slightly back to lockout"], commonMistakes: ["Bouncing bar off chest", "Flaring elbows to 90 degrees", "Losing shoulder blade retraction", "Uneven pressing"], primaryMuscles: ["pectorals"], secondaryMuscles: ["anterior deltoids", "triceps"], tertiaryMuscles: ["core", "lats"], alternativeIds: [8, 9] },
  { name: "Incline Dumbbell Press", muscleGroup: "chest", equipment: "dumbbell", goal: "hypertrophy", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=8iPEnn-ltC8", instructions: ["Set bench to 30-45 degree incline", "Hold dumbbells at shoulder level", "Press dumbbells up and slightly together", "Lower with control to chest level", "Keep shoulder blades pinched", "Maintain slight arch in lower back"], commonMistakes: ["Bench angle too steep", "Using too heavy weight", "Not full range of motion"], primaryMuscles: ["upper pectorals"], secondaryMuscles: ["anterior deltoids", "triceps"], tertiaryMuscles: ["core"], alternativeIds: [7, 9] },
  { name: "Dumbbell Chest Fly", muscleGroup: "chest", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=eozdVDA78K0", instructions: ["Lie flat on bench with dumbbells extended above", "Slight bend in elbows throughout", "Open arms wide lowering dumbbells to sides", "Feel stretch across chest at bottom", "Squeeze chest to bring dumbbells back up", "Touch dumbbells at top position"], commonMistakes: ["Bending elbows too much (turns into press)", "Going too heavy", "Not controlling the eccentric"], primaryMuscles: ["pectorals"], secondaryMuscles: ["anterior deltoids"], tertiaryMuscles: ["biceps"], alternativeIds: [7, 8] },
  { name: "Overhead Press", muscleGroup: "shoulders", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=2yjwXTZQDDI", instructions: ["Grip bar at shoulder width in rack position", "Brace core and squeeze glutes", "Press bar overhead in straight line", "Push head through once bar passes forehead", "Lock out arms fully overhead", "Lower bar under control to starting position"], commonMistakes: ["Excessive back arching", "Pressing bar forward instead of straight up", "Not bracing core properly"], primaryMuscles: ["anterior deltoids", "medial deltoids"], secondaryMuscles: ["triceps", "upper pectorals"], tertiaryMuscles: ["core", "traps"], alternativeIds: [11, 12] },
  { name: "Lateral Raise", muscleGroup: "shoulders", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo", instructions: ["Stand holding dumbbells at sides", "Slight bend in elbows", "Raise arms out to sides to shoulder height", "Lead with elbows, not hands", "Pause briefly at top", "Lower with control"], commonMistakes: ["Using momentum/swinging", "Shrugging shoulders up", "Raising arms too high"], primaryMuscles: ["medial deltoids"], secondaryMuscles: ["anterior deltoids", "traps"], tertiaryMuscles: ["forearms"], alternativeIds: [10, 12] },
  { name: "Face Pull", muscleGroup: "shoulders", equipment: "cable", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=rep-qVOkqgk", instructions: ["Set cable at upper chest height with rope", "Grip rope with overhand grip", "Pull rope toward face separating hands", "Externally rotate shoulders at end", "Squeeze rear delts and hold", "Return with control"], commonMistakes: ["Using too much weight", "Not separating the rope ends", "Pulling too low"], primaryMuscles: ["rear deltoids"], secondaryMuscles: ["traps", "rhomboids"], tertiaryMuscles: ["biceps", "rotator cuff"], alternativeIds: [10, 11] },
  { name: "Barbell Row", muscleGroup: "back", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=FWJR5Ve8bnQ", instructions: ["Hinge at hips with slight knee bend", "Grip bar slightly wider than shoulder-width", "Pull bar to lower chest/upper abdomen", "Squeeze shoulder blades together at top", "Lower bar with control", "Maintain flat back throughout"], commonMistakes: ["Using too much body English", "Not pulling to the right spot", "Rounding the back"], primaryMuscles: ["lats", "rhomboids"], secondaryMuscles: ["traps", "rear deltoids"], tertiaryMuscles: ["biceps", "forearms", "core"], alternativeIds: [14, 15] },
  { name: "Pull-Up", muscleGroup: "back", equipment: "bodyweight", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=eGo4IYlbE5g", instructions: ["Hang from bar with overhand grip wider than shoulders", "Retract shoulder blades down and back", "Pull chest toward the bar", "Drive elbows down and back", "Chin over bar at top", "Lower with full control to dead hang"], commonMistakes: ["Kipping or swinging", "Not going full range of motion", "Shrugging shoulders at the top"], primaryMuscles: ["lats"], secondaryMuscles: ["biceps", "rhomboids"], tertiaryMuscles: ["forearms", "core", "rear deltoids"], alternativeIds: [13, 15] },
  { name: "Seated Cable Row", muscleGroup: "back", equipment: "cable", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=GZbfZ033f74", instructions: ["Sit with feet on platform, slight knee bend", "Grip handle with neutral grip", "Pull handle to lower chest", "Squeeze shoulder blades together", "Extend arms with control", "Maintain upright posture throughout"], commonMistakes: ["Leaning too far forward or back", "Rounding shoulders", "Using momentum"], primaryMuscles: ["lats", "rhomboids"], secondaryMuscles: ["traps", "rear deltoids"], tertiaryMuscles: ["biceps", "forearms"], alternativeIds: [13, 14] },
  { name: "Barbell Curl", muscleGroup: "arms", equipment: "barbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=kwG2ipFRgFo", instructions: ["Stand with feet hip-width apart", "Grip barbell with underhand grip", "Keep elbows pinned to sides", "Curl bar up to shoulder level", "Squeeze biceps at top", "Lower with control"], commonMistakes: ["Swinging the body", "Moving elbows forward", "Not controlling the negative"], primaryMuscles: ["biceps"], secondaryMuscles: ["forearms"], tertiaryMuscles: ["anterior deltoids"], alternativeIds: [17, 18] },
  { name: "Hammer Curl", muscleGroup: "arms", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=zC3nLlEvin4", instructions: ["Hold dumbbells with neutral (palms facing) grip", "Keep elbows pinned to sides", "Curl dumbbells up simultaneously", "Squeeze at top of movement", "Lower with control", "Maintain neutral wrist position"], commonMistakes: ["Using momentum", "Rotating wrists during curl", "Letting elbows drift forward"], primaryMuscles: ["biceps", "brachialis"], secondaryMuscles: ["forearms"], tertiaryMuscles: ["anterior deltoids"], alternativeIds: [16, 18] },
  { name: "Tricep Dip", muscleGroup: "arms", equipment: "bodyweight", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=wjUmnZH528Y", instructions: ["Grip parallel bars and support your weight", "Lean slightly forward", "Lower body by bending elbows to 90 degrees", "Keep elbows close to body", "Press back up to full arm extension", "Control the descent"], commonMistakes: ["Going too deep", "Flaring elbows excessively", "Not leaning forward enough"], primaryMuscles: ["triceps"], secondaryMuscles: ["anterior deltoids", "pectorals"], tertiaryMuscles: ["core"], alternativeIds: [16, 17] },
  { name: "Leg Press", muscleGroup: "legs", equipment: "machine", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ", instructions: ["Sit in leg press with back flat against pad", "Place feet shoulder-width on platform", "Release safety handles", "Lower platform by bending knees", "Lower until knees are at 90 degrees", "Press through full foot to extend"], commonMistakes: ["Going too deep and lifting hips", "Locking knees at top", "Feet too high or low on platform"], primaryMuscles: ["quadriceps"], secondaryMuscles: ["glutes", "hamstrings"], tertiaryMuscles: ["adductors"], alternativeIds: [1, 3] },
  { name: "Leg Curl", muscleGroup: "legs", equipment: "machine", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs", instructions: ["Lie face down on leg curl machine", "Position pad just above ankles", "Curl weight up by bending knees", "Squeeze hamstrings at top", "Lower with control", "Keep hips pressed into pad"], commonMistakes: ["Lifting hips off pad", "Using momentum", "Not full range of motion"], primaryMuscles: ["hamstrings"], secondaryMuscles: ["calves"], tertiaryMuscles: ["glutes"], alternativeIds: [5, 21] },
  { name: "Leg Extension", muscleGroup: "legs", equipment: "machine", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0", instructions: ["Sit in machine with back against pad", "Position pad on front of ankles", "Extend legs fully", "Squeeze quadriceps at top", "Lower with control", "Don't use momentum"], commonMistakes: ["Using too much weight", "Not full extension", "Swinging legs up"], primaryMuscles: ["quadriceps"], secondaryMuscles: [], tertiaryMuscles: ["hip flexors"], alternativeIds: [1, 19] },
  { name: "Bulgarian Split Squat", muscleGroup: "legs", equipment: "dumbbell", goal: "hypertrophy", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=2C-uNgKwPLE", instructions: ["Stand in front of bench with one foot behind on bench", "Hold dumbbells at sides", "Lower back knee toward floor", "Front knee tracks over toes", "Drive through front foot to stand", "Complete all reps then switch legs"], commonMistakes: ["Standing too close to bench", "Front knee going past toes excessively", "Leaning forward too much"], primaryMuscles: ["quadriceps", "glutes"], secondaryMuscles: ["hamstrings", "adductors"], tertiaryMuscles: ["core", "calves"], alternativeIds: [1, 23] },
  { name: "Walking Lunge", muscleGroup: "legs", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=L8fvypPrzzs", instructions: ["Hold dumbbells at sides", "Step forward into lunge position", "Lower back knee toward ground", "Push off front foot to step forward", "Alternate legs with each step", "Keep torso upright"], commonMistakes: ["Taking too short of steps", "Letting front knee cave in", "Leaning forward"], primaryMuscles: ["quadriceps", "glutes"], secondaryMuscles: ["hamstrings"], tertiaryMuscles: ["core", "calves"], alternativeIds: [22, 1] },
  { name: "Cable Fly", muscleGroup: "chest", equipment: "cable", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=Iwe6AmxVf7o", instructions: ["Set cables at shoulder height", "Step forward with split stance", "Extend arms to sides with slight elbow bend", "Bring hands together in arc motion", "Squeeze chest at center", "Return slowly to stretched position"], commonMistakes: ["Bending elbows too much", "Leaning too far forward", "Going too heavy"], primaryMuscles: ["pectorals"], secondaryMuscles: ["anterior deltoids"], tertiaryMuscles: ["biceps"], alternativeIds: [9, 7] },
  { name: "Lat Pulldown", muscleGroup: "back", equipment: "cable", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc", instructions: ["Grip bar wider than shoulder-width", "Sit with thighs secured under pads", "Pull bar down to upper chest", "Lead with elbows driving down", "Squeeze lats at bottom", "Extend arms fully at top"], commonMistakes: ["Pulling behind the neck", "Leaning too far back", "Using momentum"], primaryMuscles: ["lats"], secondaryMuscles: ["biceps", "rhomboids"], tertiaryMuscles: ["forearms", "rear deltoids"], alternativeIds: [14, 15] },
  { name: "Dumbbell Shoulder Press", muscleGroup: "shoulders", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog", instructions: ["Sit on bench with back support", "Hold dumbbells at shoulder height", "Press dumbbells overhead", "Bring dumbbells together at top", "Lower to shoulder height", "Keep core braced throughout"], commonMistakes: ["Arching back excessively", "Not going full range", "Uneven pressing"], primaryMuscles: ["anterior deltoids", "medial deltoids"], secondaryMuscles: ["triceps"], tertiaryMuscles: ["upper pectorals", "traps"], alternativeIds: [10, 11] },
  { name: "Skull Crusher", muscleGroup: "arms", equipment: "barbell", goal: "hypertrophy", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=d_KZxkY_0cM", instructions: ["Lie on bench holding EZ bar overhead", "Keep upper arms perpendicular to floor", "Lower bar by bending elbows toward forehead", "Keep elbows pointed up, not flaring", "Extend arms back to starting position", "Control the weight throughout"], commonMistakes: ["Flaring elbows", "Moving upper arms", "Going too heavy"], primaryMuscles: ["triceps"], secondaryMuscles: ["forearms"], tertiaryMuscles: ["anterior deltoids"], alternativeIds: [18, 28] },
  { name: "Tricep Pushdown", muscleGroup: "arms", equipment: "cable", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU", instructions: ["Stand facing cable machine with rope or bar attachment", "Keep elbows pinned to sides", "Push weight down extending elbows fully", "Squeeze triceps at bottom", "Allow weight to return slowly", "Don't let elbows move forward"], commonMistakes: ["Using body weight to push down", "Elbows drifting forward", "Not full extension"], primaryMuscles: ["triceps"], secondaryMuscles: ["forearms"], tertiaryMuscles: ["core"], alternativeIds: [27, 18] },
  { name: "Plank", muscleGroup: "core", equipment: "bodyweight", goal: "strength", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=ASdvN_XEl_c", instructions: ["Start in pushup position on forearms", "Keep body in straight line from head to heels", "Engage core and squeeze glutes", "Don't let hips sag or pike up", "Breathe steadily", "Hold for prescribed time"], commonMistakes: ["Hips sagging", "Looking up (straining neck)", "Holding breath"], primaryMuscles: ["core", "transverse abdominis"], secondaryMuscles: ["shoulders", "glutes"], tertiaryMuscles: ["quadriceps", "lower back"], alternativeIds: [30, 31] },
  { name: "Cable Crunch", muscleGroup: "core", equipment: "cable", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=AV5PmrIhMCQ", instructions: ["Kneel below cable with rope attachment", "Hold rope behind head", "Crunch down bringing elbows to knees", "Focus on flexing the spine", "Return to upright slowly", "Keep hips stationary"], commonMistakes: ["Pulling with arms instead of abs", "Moving hips instead of curling spine", "Going too fast"], primaryMuscles: ["rectus abdominis"], secondaryMuscles: ["obliques"], tertiaryMuscles: ["hip flexors"], alternativeIds: [29, 31] },
  { name: "Hanging Leg Raise", muscleGroup: "core", equipment: "bodyweight", goal: "strength", difficulty: "advanced", youtubeUrl: "https://www.youtube.com/watch?v=hdng3Nm1x_E", instructions: ["Hang from pull-up bar with straight arms", "Keep legs straight or slightly bent", "Raise legs to parallel or higher", "Control the movement, no swinging", "Lower legs slowly", "Engage core throughout"], commonMistakes: ["Swinging excessively", "Using hip flexors only", "Not controlling descent"], primaryMuscles: ["rectus abdominis", "hip flexors"], secondaryMuscles: ["obliques"], tertiaryMuscles: ["forearms", "lats"], alternativeIds: [29, 30] },
  { name: "Hip Thrust", muscleGroup: "legs", equipment: "barbell", goal: "hypertrophy", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=SEdqd1n0cvg", instructions: ["Sit on floor with upper back against bench", "Roll barbell over hips with pad", "Plant feet flat, hip-width apart", "Drive through heels lifting hips", "Squeeze glutes hard at top", "Lower hips with control"], commonMistakes: ["Hyperextending lower back", "Feet too far away", "Not squeezing at top"], primaryMuscles: ["glutes"], secondaryMuscles: ["hamstrings"], tertiaryMuscles: ["core", "quadriceps"], alternativeIds: [22, 5] },
  { name: "Calf Raise", muscleGroup: "legs", equipment: "machine", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=gwLzBJYoWlI", instructions: ["Stand on calf raise machine or step", "Position balls of feet on edge", "Rise up on toes as high as possible", "Pause and squeeze at top", "Lower slowly getting full stretch", "Repeat for prescribed reps"], commonMistakes: ["Bouncing at bottom", "Not going through full range", "Going too fast"], primaryMuscles: ["calves"], secondaryMuscles: [], tertiaryMuscles: ["tibialis anterior"], alternativeIds: [34] },
  { name: "Seated Calf Raise", muscleGroup: "legs", equipment: "machine", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=JbyjNymZOt0", instructions: ["Sit in seated calf raise machine", "Place balls of feet on platform", "Release safety and lower heels", "Get full stretch at bottom", "Press up onto toes", "Squeeze calves at top"], commonMistakes: ["Not full range of motion", "Going too fast", "Using too much weight"], primaryMuscles: ["soleus", "calves"], secondaryMuscles: [], tertiaryMuscles: ["tibialis anterior"], alternativeIds: [33] },
  { name: "Chest Dip", muscleGroup: "chest", equipment: "bodyweight", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=2z8JmcrW-As", instructions: ["Grip parallel bars and support weight", "Lean forward about 30 degrees", "Lower body until upper arms are parallel", "Keep elbows slightly flared", "Press back up to starting position", "Maintain forward lean throughout"], commonMistakes: ["Staying too upright (shifts to triceps)", "Going too deep", "Swinging body"], primaryMuscles: ["pectorals"], secondaryMuscles: ["triceps", "anterior deltoids"], tertiaryMuscles: ["core"], alternativeIds: [7, 8] },
  { name: "T-Bar Row", muscleGroup: "back", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=j3Igk5nyZE4", instructions: ["Straddle the T-bar or landmine", "Grip the handles or use V-grip", "Hinge at hips with flat back", "Pull weight to chest", "Squeeze shoulder blades", "Lower with control"], commonMistakes: ["Standing too upright", "Using momentum", "Rounding back"], primaryMuscles: ["lats", "rhomboids"], secondaryMuscles: ["traps", "rear deltoids"], tertiaryMuscles: ["biceps", "forearms"], alternativeIds: [13, 14] },
  { name: "Dumbbell Row", muscleGroup: "back", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=pYcpY20QaE8", instructions: ["Place one knee and hand on bench", "Hold dumbbell in opposite hand", "Pull dumbbell to hip", "Squeeze lat at top", "Lower with control", "Keep back flat throughout"], commonMistakes: ["Rotating torso", "Not pulling to hip", "Using too much body English"], primaryMuscles: ["lats"], secondaryMuscles: ["rhomboids", "rear deltoids"], tertiaryMuscles: ["biceps", "forearms"], alternativeIds: [13, 15] },
  { name: "Reverse Fly", muscleGroup: "shoulders", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=lPt0GqwaqEw", instructions: ["Bend forward at hips with flat back", "Hold dumbbells hanging below chest", "Raise dumbbells out to sides", "Lead with elbows slightly bent", "Squeeze rear delts at top", "Lower with control"], commonMistakes: ["Using too much weight", "Straightening up during movement", "Not leading with elbows"], primaryMuscles: ["rear deltoids"], secondaryMuscles: ["rhomboids", "traps"], tertiaryMuscles: ["forearms"], alternativeIds: [12, 11] },
  { name: "Preacher Curl", muscleGroup: "arms", equipment: "barbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=fIWP-FRFNU0", instructions: ["Sit at preacher bench with armpits at top of pad", "Grip EZ bar with underhand grip", "Curl bar up toward shoulders", "Squeeze biceps at top", "Lower with full control", "Don't swing or use momentum"], commonMistakes: ["Not going full range", "Using momentum at bottom", "Coming off the pad"], primaryMuscles: ["biceps"], secondaryMuscles: ["forearms"], tertiaryMuscles: ["brachialis"], alternativeIds: [16, 17] },
  { name: "Push-Up", muscleGroup: "chest", equipment: "bodyweight", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=IODxDxX7oi4", instructions: ["Start in plank position hands shoulder-width", "Keep body in straight line", "Lower chest toward floor", "Elbows at 45 degree angle", "Press back up to starting position", "Maintain core engagement throughout"], commonMistakes: ["Sagging hips", "Flaring elbows to 90 degrees", "Not touching chest to floor", "Partial reps"], primaryMuscles: ["pectorals"], secondaryMuscles: ["triceps", "anterior deltoids"], tertiaryMuscles: ["core", "serratus anterior"], alternativeIds: [7, 35] },
  { name: "Upright Row", muscleGroup: "shoulders", equipment: "barbell", goal: "hypertrophy", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=amCU-ziHITM", instructions: ["Hold barbell with narrow overhand grip", "Stand upright with bar at thighs", "Pull bar up along body to chin level", "Lead with elbows keeping them high", "Pause at top", "Lower with control"], commonMistakes: ["Grip too narrow causing wrist pain", "Pulling too high causing impingement", "Using momentum"], primaryMuscles: ["medial deltoids", "traps"], secondaryMuscles: ["anterior deltoids", "biceps"], tertiaryMuscles: ["forearms"], alternativeIds: [11, 10] },
  { name: "Concentration Curl", muscleGroup: "arms", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=0AUGkch3tzc", instructions: ["Sit on bench with elbow on inner thigh", "Hold dumbbell with arm extended", "Curl weight up toward shoulder", "Squeeze biceps hard at top", "Lower slowly to full extension", "Complete all reps then switch"], commonMistakes: ["Using body swing", "Not full range of motion", "Elbow moving off thigh"], primaryMuscles: ["biceps"], secondaryMuscles: ["forearms"], tertiaryMuscles: ["brachialis"], alternativeIds: [16, 39] },
  { name: "Overhead Tricep Extension", muscleGroup: "arms", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=_gsUck-7M74", instructions: ["Hold dumbbell overhead with both hands", "Keep upper arms close to ears", "Lower dumbbell behind head by bending elbows", "Feel stretch in triceps", "Extend arms back to top", "Keep core tight and back straight"], commonMistakes: ["Flaring elbows out", "Arching back", "Not going deep enough"], primaryMuscles: ["triceps"], secondaryMuscles: ["forearms"], tertiaryMuscles: ["core"], alternativeIds: [27, 28] },
  { name: "Rack Pull", muscleGroup: "back", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=V8dCBIYNi14", instructions: ["Set safety pins at knee height in power rack", "Grip bar with overhand or mixed grip", "Brace core and flatten back", "Drive hips forward standing up", "Lock out at top squeezing glutes", "Lower bar back to pins with control"], commonMistakes: ["Rounding upper back", "Starting with hips too low", "Hitching the bar up"], primaryMuscles: ["lower back", "traps"], secondaryMuscles: ["glutes", "hamstrings"], tertiaryMuscles: ["forearms", "lats"], alternativeIds: [4, 5] },
  { name: "Pendlay Row", muscleGroup: "back", equipment: "barbell", goal: "strength", difficulty: "advanced", youtubeUrl: "https://www.youtube.com/watch?v=ZlRrIsoDpKg", instructions: ["Set up like a deadlift with bar on floor", "Bend over until back is parallel to floor", "Explosively pull bar to lower chest", "Touch chest then lower to floor", "Reset between each rep", "Maintain flat back position"], commonMistakes: ["Not resetting on floor", "Back not parallel enough", "Using leg drive"], primaryMuscles: ["lats", "rhomboids"], secondaryMuscles: ["traps", "rear deltoids"], tertiaryMuscles: ["biceps", "core"], alternativeIds: [13, 36] },
  { name: "Close-Grip Bench Press", muscleGroup: "arms", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=nEF0bv2FW94", instructions: ["Lie on bench with hands shoulder-width apart", "Unrack bar with arms locked out", "Lower bar to lower chest keeping elbows tucked", "Touch chest lightly", "Press back up focusing on triceps", "Lock out arms at top"], commonMistakes: ["Grip too narrow causing wrist strain", "Flaring elbows", "Bouncing off chest"], primaryMuscles: ["triceps"], secondaryMuscles: ["pectorals", "anterior deltoids"], tertiaryMuscles: ["core"], alternativeIds: [18, 27] },
  { name: "Good Morning", muscleGroup: "back", equipment: "barbell", goal: "strength", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=YA-h3n9L4YU", instructions: ["Position bar on upper back like a squat", "Stand with feet shoulder-width apart", "Slight bend in knees throughout", "Hinge at hips pushing them back", "Lower torso until nearly parallel", "Drive hips forward to return"], commonMistakes: ["Rounding the back", "Bending knees too much", "Going too heavy"], primaryMuscles: ["hamstrings", "lower back"], secondaryMuscles: ["glutes"], tertiaryMuscles: ["core"], alternativeIds: [5, 4] },
  { name: "Shrug", muscleGroup: "shoulders", equipment: "dumbbell", goal: "hypertrophy", difficulty: "beginner", youtubeUrl: "https://www.youtube.com/watch?v=cJRVVxmytaM", instructions: ["Hold dumbbells at sides", "Stand upright with slight forward lean", "Shrug shoulders straight up toward ears", "Hold at top and squeeze traps", "Lower slowly to starting position", "Avoid rolling shoulders"], commonMistakes: ["Rolling shoulders", "Using too much weight", "Not holding at top"], primaryMuscles: ["traps"], secondaryMuscles: ["rhomboids"], tertiaryMuscles: ["forearms", "levator scapulae"], alternativeIds: [41, 10] },
  { name: "Arnold Press", muscleGroup: "shoulders", equipment: "dumbbell", goal: "hypertrophy", difficulty: "intermediate", youtubeUrl: "https://www.youtube.com/watch?v=6Z15_WdXmVw", instructions: ["Sit with dumbbells at shoulder height palms facing you", "Press up while rotating palms to face forward", "Full lockout overhead", "Reverse the rotation coming down", "Return to starting position with palms facing you", "Smooth continuous motion throughout"], commonMistakes: ["Not rotating fully", "Going too fast", "Using too heavy weight"], primaryMuscles: ["anterior deltoids", "medial deltoids"], secondaryMuscles: ["triceps"], tertiaryMuscles: ["upper pectorals", "traps"], alternativeIds: [10, 26] },
];

async function seed() {
  console.log("Seeding exercise library...");
  
  const existing = await db.select({ id: exerciseLibraryTable.id }).from(exerciseLibraryTable).limit(1);
  if (existing.length > 0) {
    console.log("Exercise library already seeded, skipping.");
    return;
  }

  for (const exercise of exercises) {
    await db.insert(exerciseLibraryTable).values(exercise);
  }
  
  console.log(`Seeded ${exercises.length} exercises.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed error:", err);
    process.exit(1);
  });
